### ISSUE TITLE
NTR: Digestible carbohydrate

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#2]
We are going to create some nutritional framework terms in CDNO the first term is "Digestible carbohydrate" which does not exist in any other OBO ontology as far as I am aware

## Preferred term label

Digestible carbohydrate

## Textual definition

Based on Razlin's definition from Nutrition schema_framework_002:

> Also known as available carbohydrate corresponds to fractions of total carbohydrate that is digestible to provide energy. 

## Suggested parent term

[CHEBI:16646 - carbohydrate](https://www.ebi.ac.uk/chebi/searchId.do;jsessionid=E6EDC97D04EEBFE41312950A2F05D69A?chebiId=CHEBI%3A16646)

**Comment by kaiiam** [comment]
Great thanks @LilyAndres. As I understand we're going to need to add several of these terms. 

I notice that the definition you provided based on the `Nutrition schema_framework_002:` might not be complete? It is always good when formulating ontology term definitions to use an Aristotelian definition structure i.e. `A is B, which C's` e.g. `Seawater is liquid water that derives from a saline water body.`

Based on the nutrition framework this class will be subclass to CHEBI:carbohydrate, the definition of which is: 

> Any member of the class of organooxygen compounds that is a polyhydroxy-aldehyde or -ketone or a lactol resulting from their intramolecular condensation (monosaccharides); substances derived from these by reduction of the carbonyl group (alditols), by oxidation of one or more hydroxy groups to afford the corresponding aldehydes, ketones, or carboxylic acids, or by replacement of one or more hydroxy group(s) by a hydrogen atom; and polymeric products arising by intermolecular acetal formation between two or more such molecules (disaccharides, polysaccharides and oligosaccharides). Carbohydrates contain only carbon, hydrogen and oxygen atoms; prior to any oxidation or reduction, most have the empirical formula Cm(H2O)n. Compounds obtained from carbohydrates by substitution, etc., are known as carbohydrate derivatives and may contain other elements. Cyclitols are generally not regarded as carbohydrates.

We don't need to redefine carbohydrate, but we do need to differentiate what make a carbohydrate "digestible to provide energy".  

Perhaps we can try to conceive of a more specific definition of digestible carb for CDNO. 

@ramonawalls or Graham, do you have any suggestions here? Digestible to humans/other organisms, or does this mean digestible based on some specific assay? What exactly do we mean here?

**Comment by LilyAndres** [comment]
@CropStoreDb

**Comment by ramonawalls** [comment]
Graham and his colleagues will need to chime in here.

**Comment by CropStoreDb** [comment]
Agreed, and thanks - we are conferring with some domain experts to clarify these. (Graham aka @CropStoreDB)

**Comment by LilyAndres** [comment]
I'm copying what Dr. Ben Liu sent to Graham and myself.

Hi Graham,

Unfortunately, I don’t have a textbook around for this. In my opinion, digestible carbohydrate (also called available carbohydrates sometimes)  “in human nutrition” normally refers to carbohydrates which are “digestible by human digestive enzymes” and available to provide energy to human body. The values for digestible carbohydrates are normally obtained by in vitro assays by digesting complex carbohydrates to simple sugars for measurement (e.g. [https://www.megazyme.com/available-carbohydrates-dietary-fiber-assay-kit]

**Comment by kaiiam** [comment]
@LilyAndres this is a good start, we could make the term based on this info, however, if possible it would be good to find a text book definition from the discipline if it exits. I'd be surprised of there isn't one.

**Comment by LilyAndres** [comment]
I would like to propose the following definition:

> Digestible carbohydrates are a diverse group of substances with the primary function of serving as an energy source for all body cells.

ISBN 978–3–8055–8477–7
Koletzko B, et al. (eds): Pediatric Nutrition in Practice. World Rev Nutr Diet. Basel, Karger, 2015, vol 113, pp 46–50 DOI: 10.1159/000360316

**Comment by kaiiam** [comment]
@LilyAndres not a bad first pass, however, within an ontology we prefer to follow the Aristotelian genus- differentia style, i.e., An A is a B, that C's. See [this ontotips blog post](https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/) written by Chris Mungall for some more explanation. Doing this helps to figure out what the parent class should be, in this case I think the parent class should be `CHEBI:carbohydrate`. 

> substances with the primary function of serving as an energy source for all body cells.

This seem like a good pass at the differentia (that which differentiates digestible carbohydrates from more general carbohydrates), but like I said before I'm guessing there might be some operational definition for digestible in this context. Or is it really just as simple as the distinction between carbohydrates that can an cannot be metabolized? If so by what organisms (bacteria can digest lots of carbohydrates humans can't)? 

@LilyAndres would you mind adding to this thread some more of the original definition(s) presented in that `Pediatric Nutrition in Practice` book or others? So that we can have more information by which to write our definition. 

@CropStoreDb do you have any source definitions for this that you could weigh in here?

**Comment by LilyAndres** [comment]
Thanks @kaiiam, I had a look in the following references.

In the `Pediatric Nutrition in Practice` book the definition is as follows:

> Carbohydrates which provide the body with monosaccharides are defined as ‘digestible’ (available or glycaemic) 

That definition cites  `Englyst et al. 2007` [ doi:10.1038/sj.ejcn.1602937](https://www.nature.com/articles/1602937?draft\\u003dcollection) 

Checking the definition from `Englyst et al. 2007`, I found another definition where they called them available carbohydrates:

> Available carbohydrates are those that are absorbed in the small intestine and provide carbohydrate for metabolism.

Or

> Although resistant to digestion in the small intestine, non-glycaemic carbohydrates are also able to provide the body with energy through fermentation in the colon and absorption of short-chain fatty acids (SCFA) `Cummings & Stephen 2007` [doi:10.1038/sj.ejcn.1602936](https://www.nature.com/articles/1602936/) .

@CropStoreDb we might need Ben Liu to discuss this.

**Comment by LilyAndres** [comment]
Discussions with the Dr. Ben Liu concluded that the following textual definition of digestible carbohydrate is the most accurate:

> Available carbohydrates are those that are absorbed in the small intestine and provide carbohydrates for metabolism.

`Englyst et al. 2007`

@kaiiam I'm trying to develop a logical definition from here, I'm not sure if this would work. What do you think?

**Comment by LilyAndres** [comment]
Definition clean up.

Definition (A _genus_ with two _differentiae_?):

> A carbohydrate which is absorbed in the small intestine and provides carbohydrate for metabolism

`Englyst et al. 2007` 

Related synonyms:

> Available carbohydrate

Editor note:

Comment:

> Although resistant to digestion in the small intestine, non-glycaemic carbohydrates are also able to provide the body with energy through fermentation in the colon and absorption of short-chain fatty acids (SCFA)
Cummings & Stephen 2007 [doi:10.1038/sj.ejcn.1602936](https://www.nature.com/articles/1602936)

**Comment by kaiiam** [comment]
@LilyAndres 

> A carbohydrate which is absorbed in the small intestine and provides carbohydrate for metabolism

This is better, however it could still use a little cleaning up. Notice that you use `carbohydrate` twice in the sentence both as the genus and as the differentia, it's better to avoid this kind of thing. Also note the grammar in `provides carbohydrate for`. 

Noting your comment above are `non-glycaemic carbohydrates` part of digestible carbohydrates or not? If so that sort of think might influence how we define the term. 

Are these only the carbohydrates that can be broken down within certain human organs by certain metabolic processes? Does this mean carbs that can be broken down just by human metabolic processes, or more likely with the aid of our microbial flora (which I understand do a lot of the metabolic work)? Does this include all metabolic processes conducted within the human body (by us and our flora) including fermentation in the colon and absorption of short-chain fatty acids  etc (as reflected in that comment)?  

Does this only apply to Humans, not livestock (e.g., cows and their microbial flora can break down way more types of carbs then we can)? I presume our scope is only humans here but maybe that could be reflected in the label?

Perhaps (depending on the small intestine vs whole GI tract question) something more along the lines of:

> A carbohydrate which can be catabolized within (any part of? or just the small intestine of) the human gastrointestinal tract (via xyz reactions?) in order to provide energy and molecules for use in anabolic processes. 

Maybe a simpler version?

> A carbohydrate which can be catabolized within a (human small intestine or whole GI tract). 

@CropStoreDb any thoughts on the small intestine vs whole GI tract question?

**Comment by LilyAndres** [comment]
Hi @kaiiam 

Thanks a lot for the suggestions, we are close. 

> Noting your comment above are non-glycaemic carbohydrates part of digestible carbohydrates or not? If so that sort of think might influence how we define the term.

I think the previous paragraph before `Although resistant to digestion in the small intestine, non-glycaemic carbohydrates are also.....  would help.

> Carbohydrates which provide the body with monosaccharides are defined as ‘digestible’ (available or glycaemic) and carbohydrates that resist digestion in the small intestine or are poorly absorbed are called ‘resistant’ (unavailable or non- glycaemic) (Englyst et al. 2007). However, although resistant to digestion in the small intestine, non-glycaemic carbohydrates are also able to provide the body with energy through fermentation in the colon and absorption of short-chain fatty acids (SCFA) (Cummings & Stephen 2007).

Also according to Cherian G., 2009, it seems that the digestion of these carbohydrates occurs mainly in the small intestine by the pancreatic amylase and di/oligosaccharidases [link](https://open.oregonstate.education/animalnutrition/chapter/chapter-4/)

![image](https://user-images.githubusercontent.com/25215773/94119811-bd21a300-fe92-11ea-9393-6302b0302d01.png)

**Comment by kaiiam** [comment]
Great @LilyAndres I think these are the references and details we were lacking. If I'm understanding this correctly `Cummings & Stephen 2007` only refer to `digestible carbs` as those metabolized in the small intestine? Because those carbs that can't be digested in the small intestine are called `resistant`?

This fits with the `Englyst et al. 2007`'s definition you'd mentioned earlier:

> Available carbohydrates are those that are absorbed in the small intestine and provide carbohydrate for metabolism.

Can we confirm (or do we know) that the Nutritional Framework Terms (NFTs) that you want to state as being subclasses of `digestible carbs` are in fact absorbed in the small intestine, and not fermented in the large intestine? 

Ideally we'd have classes for both `resistant` and `digestible` carbs, I see the NFTs also include `non digestible carbohydrate` (xref https://github.com/Southern-Cross-Plant-Science/cdno/issues/6). Does this correspond to the `resistant` carbs described by `Cummings & Stephen 2007`? Are these `resistant` carbs only fermented in the colon/large intestine? If so we have a clear separation. Or do your NFTs `non digestible carbohydrate` terms mean something different like they are a source of dietary fiber, but aren't fermented in the colon. 

I take it `non digestible carbohydrates` don't refer to things like hay that I presume wouldn't provide dietary fiber or provide energy via fermentation? If so maybe those should be called  `resistant` instead of `non digestible`? I'm not the expert here someone please correct me if I'm missing something.

**Comment by LilyAndres** [comment]
@kaiiam Sorry for my long response, I hope it's clear. I think you have important points to discuss: 

> If I'm understanding this correctly Cummings & Stephen 2007 only refer to digestible carbs as those metabolized in the small intestine? Because those carbs that can't be digested in the small intestine are called resistant?

**Yes, that's correct.**
Also, I'm thinking that it could be neccesary to add the term "**in monogastric animals**" in the definition, as the carbohydrate digestion in ruminant animals is through microbial fermentation in the rumen `Cherian G., 2009`.

> Can we confirm (or do we know) that the Nutritional Framework Terms (NFTs) that you want to state as being subclasses of digestible carbs are in fact absorbed in the small intestine, and not fermented in the large intestine?

Yes, It's all correct with the terms associate it to the class "digestible carbohydrate". But I have to check the non-digestible carbohydrates: glucose derives from cellulose seems incorrect... I need to check the relationships for those terms.

> Ideally we'd have classes for both resistant and digestible carbs, I see the NFTs also include non digestible carbohydrate (xref #6). Does this correspond to the resistant carbs described by Cummings & Stephen 2007? 

Yes, they are also called "resistant". I think we can make a synonym? Some authors refer to them as **non-digestible or resistant.**

>Are these resistant carbs only fermented in the colon/large intestine? If so we have a clear separation. Or do your NFTs non digestible carbohydrate terms mean something different like they are a source of dietary fiber, but aren't fermented in the colon?

Yes, I think that's how we can separate them, please have a look to the info below: 

Hojsak I. 2015, defines non-digestible carbohydrates as follows (although is not the type of definition we are looking for, it might help): 

Non-Digestible (Resistant) Carbohydrates Dietary Fibres: Dietary fibres are non-digestible carbohydrates mostly derived from plant sources that reach the colon nearly intact. These compounds can be further classified into soluble types of fibre, like pec- tins, and insoluble components such as cellulose. Fibres that are added to the food and have beneficial physiological effects on humans are called ‘functional fibres’. It is not completely accurate to name fibres as non-digestible, because bacteria in the large intestine ferment mostly soluble fibres. Fermented products include gases (carbon dioxide and methane), oligofructoses as well as SCFA including acetic acid, butyric acid and propionic acid. These fermentation products derive energy for certain colonic bacteria and colonic epithelia cells which use butyrate as an energy source, even when competing substrates such as glucose are available.

So just to keep the evidence here, this image from `Englyst et al., 2007` captures the difference between "available carbohydrates (digestible carbohydrates)" and "resistant carbohydrates (non-digestible carbohydrates)". 

![digestible nondigestibleCarb](https://user-images.githubusercontent.com/25215773/94330636-a8b3e680-0009-11eb-9a26-7a4ac4872add.png)


> I take it non digestible carbohydrates don't refer to things like hay that I presume wouldn't provide dietary fiber or provide energy via fermentation? If so maybe those should be called resistant instead of non digestible? I'm not the expert here someone please correct me if I'm missing something.

I think that makes sense. I will get in contact with the team and make a decision for renaming or leaving non-digestible carbohydrates.

**Comment by kaiiam** [comment]
> add the term "in monogastric animals" in the definition
👍 

Regarding Non-Digestible (Resistant) Carbohydrates

> These compounds can be further classified into soluble types of fibre, like pectins, and insoluble components such as cellulose.

Do we want to make classes for soluble and insoluble non digestible carbohydrates (both as subclass to non digestible carbohydrate)? This seems to be a common topic of discussion in health forums. 

> It is not completely accurate to name fibres as non-digestible, because bacteria in the large intestine ferment mostly soluble fibres.

`Hojsak I. 2015` seem to be saying that for the most part only the soluble fibers are fermented by bacteria in the large intestine, but maybe they are also fermenting some insoluble fibers. I'm guessing it might not matter if we're unclear about the extent to which insolube fibres are fermented, as the differentia between the fiber classes is whether or not they are water soluble. 

I see that the NFTs currently have `cellulose`, `hemicellulose`, `fructan`, `pectin` and `raffinose family of oligosaccharide (rfo)` as `non digestible carbohydrate`. I presume that the first 2 are insoluble fibers and the rest soluble?

I see that under the NFT 4th level terms `cellulose`, `hemicellulose`, there a variety of sugars in the 5th level `glucose`, `mannan`, `xylan`, etc. My understanding is that in the NFTs these 5th level sugars are derived from the 4th level molecules (via some chemical processes in the lab) in order to get an estimate of how much energy is available? Is that correct? If not how were these derived? My question is do we actually know if for example the `mannan` and `mannose` from `hemicellulose` is actually being used/release/fermented by us or our gut bacteria? Or are these just estimates of how much energy could be available if we were to break these compounds down. If you guys could help me understand the theory about how/why these NFTs were created it would help to define the higher level terms ontologically. Even if the NFTs are just lab estimates of calories released from various carbohydrate bi-products it would be idea to be really clear about what you mean by `digestible carbohydrate` and `non digestible carbohydrate`, as I presume we're giving some sort of calculation or estimate of these concepts.

**Comment by LilyAndres** [comment]
We will use the definition from `Englyst et al. 2007` to describe available carbohydrate, adding that this definition applied for "monogastric animals" as it is mentioned by `Cherian G., 2009`.

Definition 

"Available carbohydrates are those that are absorbed in the small intestine and provide carbohydrate for metabolism in monogastric animals"

**Comment by kaiiam** [comment]
Great @LilyAndres this sounds good! if I could suggest just a little change the structure the sentence as `A B which C's`. 

> Carbohydrates which are absorbed in the small intestine and provide carbohydrate for metabolism in monogastric animals.

**Comment by kaiiam** [comment]
@LilyAndres be sure to check out [ENVO-Robot-template-and-merge-workflow](https://github.com/EnvironmentOntology/envo/wiki/ENVO-Robot-template-and-merge-workflow), especially the section about [definitions](https://github.com/EnvironmentOntology/envo/wiki/ENVO-Robot-template-and-merge-workflow#definitions) should hopefully help you as you fill out the remaining terms in the NCF.

**Comment by LilyAndres** [comment]
I'm sorry I wasn't mean to close the issue. Thanks @kaiiam, I saw the workflow, it's awesome, clear and concise, definitely helpful. I will make the definitions as `'A B which C's'`, after I report the formal definition. 

> Great @LilyAndres this sounds good! if I could suggest just a little change the structure of the sentence as `A B which C's`.
> 
> > Carbohydrates which are absorbed in the small intestine and provide carbohydrate for metabolism in monogastric animals.

Stupendous! I copied this definition in the ROBOT template.

**Comment by kaiiam** [comment]
> Thanks @kaiiam, I saw the workflow,  ... I will make the definitions as 'A B which C's', after I report the formal definition.

Awesome thanks @LilyAndres hope it can guide you.

> Stupendous! I copied this definition in the ROBOT template.

Great, I guess `digestible carbohydrate` ended up as `available carbohydrate`. Did you want to make the former a synonym if people also use that term interchangeably? 

Once @LilyAndres  you're finished with  `available carbohydrate` in the robot template go ahead and close this issue.

**Comment by LilyAndres** [comment]
> Great, I guess digestible carbohydrate ended up as available carbohydrate. Did you want to make the former a synonym if people also use that term interchangeably?

Yes, I think that sounds good, I added "digestible carbohydrate" as a synonym in the ROBOT Template. 

Thanks, I'm closing this issue now.

**Comment by kaiiam** [comment]
@LilyAndres just make sure to add the relevant citations in the `definition cross reference` column.
