### ISSUE TITLE
CDNO physical attribute class

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#67]
## Preferred term label

physical attribute

## Textual definition

A physical property that inheres in a food material or one or more dietary nutritional component

## Suggested parent term

'specifically dependent continuant' [BFO:0000020]

## Attribution

https://orcid.org/0000-0002-5975-6051

**Comment by CropStoreDb** [comment]
This is one of the proposed classes where 'physical property' is initially suggested _sensu_ http://purl.obolibrary.org/obo/NCIT_C158424 (Any of the characteristics that define the nature of matter or forces that act upon it) and is distinct from the proposed 'functional attribute' class. One would expect terms such as 'energy', 'specific gravity' to be included in this class.

**Comment by kaiiam** [comment]
Based on what @LilyAndres said above I'd say this class should be (following her correct use of BFO 👍 ) subclass to PATO [quality](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000001&viewMode=PreferredRoots&siblings=false) or [physical object quality](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001241&viewMode=PreferredRoots&siblings=false). 

The latter has subclass [energy](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001021). At the moment unfortunatly PATO is missing `specific gravity` but that could be added. @CropStoreDb since OBO ontologies are suppose to be domain specific and interoperable we the nutrition ontology shouldn't be creating those physics terms but instead be importing them from ontologies they belong to in this case I believe PATO is best. 

Interestingly ENVO also has an [energy](https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_2000015) but as a BFO:`disposition` (rather than quality), with an editors note saying it should go to PATO or COB, and have a physicist sort out where it should be. I think for now we should stick to PATO for these sorts of things.

**Comment by kaiiam** [comment]
I would maybe rework the label or definition though to either both or neither refer to food materials. E.g.  something like `physical food attribute`, or `physical food quality` or similar to fit the definition above.

**Comment by LilyAndres** [comment]
A new draft with terms for this class can be found in the following[ link](https://docs.google.com/spreadsheets/d/1wyP2vqzJyC0Tba0yzS_IJXG6wpVuIVQH/edit#gid=958732661), feedback anyone?

**Comment by LilyAndres** [comment]
@ddooley, @kaiiam I'm creating this class in CDNO, for now I will put it as a subclass of `specifically dependent continuant` because in COB I can't see quality or something similar... Is this ok? We can change at any point.

**Comment by ddooley** [comment]
So COB has http://purl.obolibrary.org/obo/PATO_0000001 quality but they've named it "characteristic".  I'd just import PATO_0000001 into CDNO and pop it under there.  But you also mention "physical object quality", and now I'm wondering if there is a need to add "physical attribute".  If it is specific to food/nutrition, perhaps spell it out and make it a subclass, e.g. "food related physical attribute" or "organic material attribute".  Also wondering if this encompasses information?  (I see COB includes "information representation" anticipating that some things like energy, are calculated so not really immediately observed.)

**Comment by LilyAndres** [comment]
Thanks @ddooley,`information representation` doesn't have a definition the examples help but I'm not fully convinced with it. I think we will just rework the label as @kaiiam mentioned, @Graham-J-King what do you think about the labels "food related physical attribute", "physical food attribute" or "physical food quality"?

**Comment by kaiiam** [comment]
>  I'd just import PATO_0000001 into CDNO and pop it under there.

👍  agreed

COB's  "information representation" http://purl.obolibrary.org/obo/COB_0000120 is based on IAO:  information carrier http://purl.obolibrary.org/obo/IAO_0000015 which is subclass to quality. I don't think we need to bother with that.

> need to add "physical attribute". If it is specific to food/nutrition

PATO already has the more general term `physical quality` http://purl.obolibrary.org/obo/PATO_0001018, which you could use to superclass CDNO's `physical food quality` (or whatever label you give it).  PATO [energy](http://purl.obolibrary.org/obo/PATO_0001021) is already a subclass of PATO `physical quality`. It seems the other terms @LilyAndres you propose under CDNO `physical attribute` in your sheet might also be subclasses to PATO `physical quality`. TBD I guess. I can help you add terms to PATO if needed.

**Comment by kaiiam** [comment]
To my above point @LilyAndres you've also got `specific gravity` which according to the [wiki page on relative density, or specific gravity](https://en.wikipedia.org/wiki/Relative_density) it's "the ratio of the density (mass of a unit volume) of a substance to the density of a given reference material" aka a density. So perhaps this could be added to PATO as a subclass to [mass density](http://purl.obolibrary.org/obo/PATO_0001019), then re-imported into CDNO. Please shout anyone if I'm misunderstanding the physics of this.

**Comment by LilyAndres** [comment]
Thanks @kaiiam, sounds good. I will create `physical food quality` (or whatever label we decide that is specific to "food") as a subclass of `physical quality`.

> So perhaps this could be added to PATO as a subclass to mass density, then re-imported into CDNO.

Could be... I think we still need to work with the labels and definitions for the terms within these new classes, but we will make sure that the terms that are in scope to PATO are describe in there first and then import them into CDNO.

**Comment by LilyAndres** [comment]
This term has been included in release 3.0, the name of the class is 'dietary material physical attribute'. I will close this issue now, thanks everybody for the feedback.
